version: "3"
services:
  db:
    image: postgres
    restart: unless-stopped
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: SuperSecret!23
    volumes:
      - db-data:/app/postgres:/var/lib/postgresql/data

volumes:
  db-data:
